---
- name: Configure Docker on Deployserver
  hosts: [server]
  become: true
  tasks:
  - name: apt updating
    command: sudo apt update
  - name: Install python and Pip
    apt:
      name:
        - python3
        - python3-pip
      state: present
      update_cache: yes
  - name: Install Docker
    become: true
    apt:
      name: docker.io
      state: latest
      updated_cache: yes
  - name: start docker service using systemctl
    command: sudo systemctl start docker
    become: yes
    become_user: root
  - name: Deploy the Image from DockerHub and Run as Container
    command: docker run -itd -p 8080:8081 30adi/insure-me:1.0
