---
- name: Configure Docker on Deployserver
  hosts: [server]
  become: true
  tasks:
  - name: apt updating
    command: sudo apt update
  - name: Install python and Pip
    apt:
      name:
        - python3
        - python3-pip
      state: present
      update_cache: yes
 - name: Install prerequisites for Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  - name: Add Docker GPG key
    command: >
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    args:
      creates: /usr/share/keyrings/docker-archive-keyring.gpg
  - name: Add Docker repository
    apt_repository:
      repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
      state: present
  - name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  - name: start docker service using systemctl
    command: sudo systemctl start docker
    become: yes
    become_user: root
  - name: Deploy the Image from DockerHub and Run as Container
    command: docker run -itd -p 8080:8081 30adi/insure-me:1.0
